[package]
name = "tasks"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
rocket_contrib = "0.4.11"
rusqlite = { version = "0.31.0", features = ["bundled"] }

