[package]
name = "tasks"
version = "0.1.0"
edition = "2021"

[dependencies]
<<<<<<< HEAD
rocket = { version = "0.5.1", features = ["json"] }
rocket_contrib = "0.4.11"
rusqlite = { version = "0.31.0", features = ["bundled"] }

=======
rocket = "0.5.1"
>>>>>>> 0801959 (tasks repo for todo app with rust stack)
